__version__ = "0.6.24"

# Hard economy goal.
WOOD_FOR_WATER_BOOST = 3200
wood_for_water_boost = WOOD_FOR_WATER_BOOST

# Resource safety buffers.
MIN_HAY_BUFFER = 300
MIN_HAY_BUFFER_LATE = 450
MIN_CARROT_BUFFER = 450
MIN_CARROT_BUFFER_WITH_PUMPKIN = 700
PUMPKIN_CARROT_BUFFER = 1600
HAY_RECOVERY_EXIT_MARGIN = 60
CARROT_RECOVERY_EXIT_MARGIN = 90
PUMPKIN_ENABLE_MARGIN = 120

# Strategy scheduler policy.
ENABLE_PRIORITY_SCHEDULER = True
ENABLE_MODE_LOCK = True
MODE_MIN_HOLD_LOOPS = 3
SCORE_HAY_RECOVERY = 950
SCORE_CARROT_RECOVERY = 900
SCORE_MAZE_FOCUS = 880
SCORE_TREE_BOOST = 820
SCORE_SUNFLOWER = 760
SCORE_CACTUS = 740
SCORE_POLYCULTURE = 700
SCORE_TREE_FALLBACK = 420
SCORE_BUSH_FALLBACK = 300

# Locked-goal planner policy.
ENABLE_LOCKED_MODULE = True
LOCKED_REQUIRE_COSTS_UNLOCK = True
LOCKED_PRIORITY_BONUS = 260
LOCKED_GOLD_PRIORITY_BONUS = 320

# Runtime status output policy.
ENABLE_STATUS_OUTPUT = True
STATUS_OUTPUT_EVERY_LOOPS = 10

# Polyculture policy.
ENABLE_POLYCULTURE_MODE = True
POLYCULTURE_WOOD_HEADROOM = 500
POLYCULTURE_CARROT_HEADROOM = 300
ENABLE_RANDOM_POLYCULTURE = True
RANDOM_POLY_TREE_CHANCE = 0.25
RANDOM_POLY_CARROT_CHANCE = 0.30
RANDOM_POLY_BUSH_CHANCE = 0.25

# Sunflower policy.
ENABLE_SUNFLOWER_MODE = True
MIN_POWER_BUFFER = 250
SUNFLOWER_DISABLE_MARGIN = 80
SUNFLOWER_WOOD_HEADROOM = 250
SUNFLOWER_TIME_CYCLE = 120
SUNFLOWER_ACTIVE_SECONDS = 70

# Cactus policy.
ENABLE_CACTUS_MODE = True
MIN_CACTUS_BUFFER = 200
CACTUS_DISABLE_MARGIN = 120
CACTUS_WOOD_HEADROOM = 600
CACTUS_CARROT_HEADROOM = 200
CACTUS_TIME_CYCLE = 180
CACTUS_ACTIVE_SECONDS = 90

# Dinosaur preparation policy.
DINOSAUR_CACTUS_BUFFER = 1200

# Maze preparation policy.
ENABLE_MAZE_PREP_MODE = True
MAZE_PREP_WEIRD_SUBSTANCE_TARGET = 1000
MAZE_PREP_FERTILIZER_TARGET = MAZE_PREP_WEIRD_SUBSTANCE_TARGET
MAZE_PREP_DISABLE_PUMPKINS = True
MAZE_PREP_DISABLE_CACTUS = True
MAZE_PREP_USE_FERTILIZER = True

# Post-maze policy.
ENABLE_FERTILIZER_AFTER_MAZE = True
MIN_WEIRD_SUBSTANCE_BUFFER = 1200

# Tree policy.
TREE_WOOD_HEADROOM = 900

# Timing policy.
ENABLE_TIME_PHASES = True
EARLY_GAME_SECONDS = 180
EARLY_TREE_EXTRA_HEADROOM = 400
EARLY_DISABLE_SUNFLOWERS = True
EARLY_DISABLE_PUMPKINS = True

# Area / mode tuning.
PUMPKIN_MIN_SIZE = 6
PUMPKIN_MAX_SIZE = 8
PUMPKIN_FORCE_RESEED_EVERY = 35
PUMPKIN_TIME_CYCLE = 150
PUMPKIN_ACTIVE_SECONDS = 90

# Watering policy.
ENABLE_WATERING = True
WATER_TARGET = 0.45
WATER_TARGET_PUMPKIN = 0.70

# Fertilizer policy.
ENABLE_FERTILIZER = False
MIN_FERTILIZER_STOCK = 25

# Hat rotation policy.
ENABLE_HAT_ROTATION = True
HAT_CHANGE_EVERY_LOOPS = 8
USE_RANDOM_HATS = True
HAT_REQUIRE_UNLOCK = False
HAT_CHANGE_ON_FIRST_LOOP = True

# Compatibility fallbacks for pre-Expand2 phases.
FALLBACK_WORLD_SIZE = 6
FALLBACK_LINE_TILES = 6
